version: 2
updates:
  - package-ecosystem: "github-actions"
    # target-branch: develop
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - github actions dependencies
  - package-ecosystem: npm
    # target-branch: develop
    directories:
      - "/applications/*"
    schedule:
      interval: "weekly"
    labels:
      - npm dependencies
