name: setup

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - name: setup nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: get lockfile path
        run: echo "LOCKFILE_PATH=${{ inputs.dir }}/package-lock.json" >> $GITHUB_ENV
      - name: setup cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dir }}/node_modules
          key: app-${{ hashFiles(env.LOCKFILE_PATH) }}
      - name: install node dependencies
        run: npm install
