permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  # Allows manually triggering the workflow
  workflow_dispatch:

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: check
jobs:
  format:
    strategy:
      matrix:
        dir: [applications/map]
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: setup nix
        uses: nicknovitski/nix-develop@v1
      - name: install dependencies
        run: npm install
      - name: format
        run: npm run format 
