# This workflow runs whenever a PR is opened or updated, or a commit is pushed to main. It runs
# several test suites:
# - unit-test: checks that the unit tests passes
#
# Inspired by https://github.com/jonhoo/rust-ci-conf

# This workflow need to read the repository, write to GitHub Container Registry
# and make use of actions defined elswhere
permissions:
  contents: read
  packages: write
  actions: read

# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches:
      - main
    paths:
      - applications/*
  # Allows manually triggering the workflow
  workflow_dispatch:

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: publish container image
jobs:
  publish:
    strategy:
      matrix:
        dir: [applications/map]
    runs-on: ubuntu-24.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image with Nix
        run: |
          nix build .#container
          docker load < result
      - name: Tag Docker Image (latest)
        run: |
          IMAGE_ID=$(docker images -q | head -n 1)
          docker tag $IMAGE_ID ghcr.io/${{ github.repository }}/${{ matrix.dir }}:latest
      - name: Push Docker Image (latest)
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ matrix.dir }}:latest
